<a href="https://colab.research.google.com/github/Dorji-Yangzom/Dorji-Yangzom/blob/main/2D_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Quiz on 2D Numpy Array

Consider the following list a, convert it to Numpy Array.

In [ ]:
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [4]:
import numpy as np

# Given list
a = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]

# Convert to 2D NumPy array
arr = np.array(a)

# Print the array
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Calculate the numpy array size.

In [5]:
import numpy as np

a = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]

arr = np.array(a)

# Calculate size
print("Size of the array:", arr.size)


Size of the array: 12


Access the element on the first row and first and second columns.

In [6]:
import numpy as np

a = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]

arr = np.array(a) # converting to numpy array

# Access elements: first row, first and second columns
elements = arr[0, 0:2]  # row 0, columns 0 and 1
print("Elements on first row, first and second columns:", elements)


Elements on first row, first and second columns: [1 2]


Perform matrix multiplication with the numpy arrays A and B.

In [ ]:
A = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

In [8]:
import numpy as np

# A from the previous list
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[0, 1],
              [1, 0],
              [1, 1],
              [-1, 0]])

# matrix multiplication
C = np.matmul(A, B)  # or A @ B
print("Result:\n", C)


Result:
 [[ 1  4]
 [ 5 12]
 [ 9 20]]
